idea_tracker/config/routes.rb
IdeaTracker::Application.routes.draw do
  resources :statuses
  resources :settings

  get 'keywords/:keyword', to: 'ideas#index', as: :keyword

  match '/category/', :to => 'category#index', :as => :categories, :via => [:get]
  resources :category  
  resources :partners

  resources :ideas

  devise_for :users

  mount Commontator::Engine => '/commontator'
  get "comments/index"
  get "comments/show"
  get "comments/new"
  get "comments/edit"
  get "comments/delete"
  get "users/index"
  get "ideas/index"
  get "ideas/show"
  get "ideas/new"
  get "ideas/edit"
  get "ideas/delete"
  get "clients/index"
  get "clients/show"
  get "clients/new"
  get "clients/edit"
  get "clients/delete"
  resources :dashboard
  get "admin/setting"
  resources :admin

  resources :users do
    resources :ideas
       get 'sendemail', :on => :collection
       get 'to_csv', :on => :collection
       get 'to_csv_all', :on => :collection
  end

  root to: "home#index"
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

idea_tracker/app/models/association.rb
class Association < ActiveRecord::Base
end

idea_tracker/app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :type, :class_name => 'CategoryType'
	belongs_to :parent, :class_name => 'Category'
	has_many :children, :class_name => 'Category', :foreign_key => 'parent_id'
	has_many :tag, :class_name => 'IdeaTag', :foreign_key => 'category_id'

	def to_s
		self.category_name
	end

	def self.get_children_by_parent_name parent_name
		parent = Category.find_by :category_name => parent_name
		if !parent.nil?
			parent.children
		else
			nil
		end
	end

	scope :top_categories, lambda { where(parent_id: 0)}
end

idea_tracker/app/models/category_type.rb
class CategoryType < ActiveRecord::Base
	self.inheritance_column = nil
	has_many :categories
end

idea_tracker/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :idea
end

idea_tracker/app/models/idea.rb
class Idea < ActiveRecord::Base
	include PublicActivity::Model
	tracked owner: ->(controller, model) {controller && controller.current_user}
	
	belongs_to :partner
	belongs_to :owner, :class_name => 'User' # this is the current owner of the idea
	belongs_to :user, :class_name => 'User' # this is the creator of the idea

	belongs_to :status
	
	has_many :partners
	has_many :comments
	has_many :child_ideas, :class_name => 'Association', :foreign_key => 'parent_idea_id'
	has_many :parent_ideas, :class_name => 'Association', :foreign_key => 'tagged_idea_id'
	has_many :participants, :class_name => 'Subscription', :foreign_key => 'idea_id'

	validates_presence_of :summary
	validates_presence_of :description
	validates_presence_of :owner

	acts_as_taggable
	acts_as_taggable_on :keyword 

	# lets to comment on ideas
	acts_as_commontable

	def parent_ideas_ids
		self.parent_ideas.where(:is_hierarchy => 1).collect {|u| u.parent_idea_id}
	end
	def child_ideas_ids
		self.child_ideas.where(:is_hierarchy => 1).collect {|u| u.tagged_idea_id}
	end
	def peer_ideas_ids
		self.child_ideas.where(:is_hierarchy => 0).collect {|u| u.tagged_idea_id}
	end

	def to_s
		self.summary.truncate(30)
	end

	# scope :recent, order("created_at desc").limit(5)
	scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }
	
	accepts_nested_attributes_for :partner
end

idea_tracker/app/models/idea_tag.rb
class IdeaTag < ActiveRecord::Base
	belongs_to :category
	belongs_to :idea
end

idea_tracker/app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :user
end

idea_tracker/app/models/partner.rb
class Partner < ActiveRecord::Base
	has_many :ideas
	
	validates :partner_name, :presence => true,
					  :length => { :maximum => 100 }					  
	validates :contact_name, :presence => true,
					  :length => { :maximum => 100 }						  
	validates :email, :presence => true,
					  :length => { :maximum => 100 },
                      :confirmation => true

	def to_s
		self.partner_name
	end
	
end

idea_tracker/app/models/setting.rb
class Setting < ActiveRecord::Base

	def self.allow_sign_up
		self.find_by_name("Allow Sign Up").data.casecmp "Yes" == 0
	end

	def self.default_owner
		self.find_by_name("Default Owner").data.to_i
	end
end

idea_tracker/app/models/status.rb
class Status < ActiveRecord::Base

	validates_presence_of :status

	def to_s
		self.status
	end
	
end

idea_tracker/app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :user
	belongs_to :idea
end

idea_tracker/app/models/tag.rb
class Tag < ActiveRecord::Base
end

idea_tracker/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ideas
  has_many :comments
  has_many :subscriptions

  # allows users to post comments
  acts_as_commontator

  after_create :register_mail
  def register_mail
  	UserMailer.welcome_email(self).deliver
  end
  def to_s
    self.first_name + " " + self.last_name
  end
  
end

idea_tracker/app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :check_user_permission
  before_action :set_partner, only: [:show, :edit, :update, :destroy]

  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Partner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @partner }
      else
        format.html { render action: 'new' }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to partners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_params
      params.require(:partner).permit(:partner_name, :contact_name, :email, :phone_num, :secondary_contact_name, :secondary_email, :secondary_phone_num)
    end
  end

idea_tracker/app/helpers/admin_helper.rb
module AdminHelper

	def gravatar_url_small(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=32"
  end

  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

end

idea_tracker/app/helpers/category_helper.rb
module CategoryHelper
end

idea_tracker/app/helpers/dashboard_helper.rb
module DashboardHelper
end

idea_tracker/app/helpers/home_helper.rb
module HomeHelper
end

idea_tracker/app/helpers/ideas_helper.rb
module IdeasHelper
end

idea_tracker/app/helpers/partners_helper.rb
module PartnersHelper
end

idea_tracker/app/helpers/reports_helper.rb
module ReportsHelper
end

idea_tracker/app/helpers/statuses_helper.rb
module StatusesHelper
end

idea_tracker/app/helpers/users_helper.rb
module UsersHelper
end

idea_tracker/app/views/partners/_form.html.erb
<% if @partner.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:</h2>
  <ul>
    <% @partner.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@partner) do |f| %>
<div class="form-group">
  <%= f.label :partner_name %>*<small>  <i class="fa fa-info-circle fa-fw"  rel="tooltip" title="Name of Organization" ></i> </small><br>
  <%= f.text_field :partner_name, :class => 'form-control' %>
</div>
<div class="row">
  <div class="col-md-6">
    <h4>Primary Contact</h4>
    <div class="form-group">
      <%= f.label :contact_name %>*<br>
      <%= f.text_field :contact_name, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>*<br>
      <%= f.email_field :email, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <label for="partner_phone_num">Phone</label><br>
      <%= f.phone_field :phone_num, :class => 'form-control' %>
    </div>
  </div>
  <div class="col-md-6">
    <h4>Secondary Contact</h4>
    <div class="form-group">
      <%= f.label :contact_name %><br>
      <%= f.text_field :secondary_contact_name, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %><br>
      <%= f.email_field :secondary_email, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <label for="partner_phone_num">Phone</label><br>
      <%= f.text_field :secondary_phone_num, :class => 'form-control' %>
    </div>
  </div>
</div>
<div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
</div>
<% end %>

idea_tracker/app/views/partners/edit.html.erb
<h1 class="page-header">Partners <small><%= @partner.partner_name %></small></h1>
<h5 class="widget">
    <%= link_to '<i class="fa fa-plus"> </i> Add a New Partner'.html_safe , new_partner_path  %> | 
    <%= link_to '<i class="fa fa-reply"></i> Back'.html_safe, partners_path %>
</h5>
<section class="widget">
    <div class="panel-body">
    <h4>Editing <%= @partner.partner_name %></h4>
       <%= render 'form' %>
   </div>
</section>


<%= link_to 'Show', @partner %> |
<%= link_to 'Back', partners_path %>

idea_tracker/app/views/partners/index.html.erb
<h1 class="page-header">Partners</h1>
<h5 class="widget">
    <%= link_to '<i class="fa fa-plus"> </i> Add a New Partner'.html_safe, new_partner_path %>
</h5>

<section class="widget">
  <div class="panel-heading"><i class="fa fa-bars"></i> List of Partners</div>
    
  <div class="panel-body">
    <div class="table">
      <table class="table table-hover dataTable">
        <thead>
          <tr>
            <th>Partner name</th>
            <th>Contact name</th>
            <th>Email</th>
            <th>Phone num</th>
            <th class="no-sort"></th>
            <th class="no-sort"></th>
            <th class="no-sort"></th>
          </tr>
        </thead>

        <tbody>
          <% @partners.each do |partner| %>
          <tr>
            <td><%= partner.partner_name %></td>
            <td><%= partner.contact_name %></td>
            <td><%= partner.email %></td>
            <td><%= partner.phone_num %></td>
            <td><%= link_to '<i class="fa fa-search"></i>'.html_safe, partner, title: 'Show', ref: 'tooltip' %></td> 
            <td><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_partner_path(partner), title: 'Edit', ref: 'tooltip' %></td>
            <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, partner, title: 'Delete', ref: 'tooltip', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </section>

idea_tracker/app/views/partners/new.html.erb
<h1 class="page-header">Partners</h1>
<h5 class="widget">
    <%= link_to '<i class="fa fa-reply"></i> Back'.html_safe, partners_path %>
</h5>
<section class="widget">
    <div class="panel-body">
        <h4>Add a New Partner</h4>
           <%= render 'form' %>

   </div>
</section>

idea_tracker/app/views/partners/show.html.erb
<h1 class="page-header">Partners <small><%= @partner.partner_name %></small></h1>
<h5 class="widget">
    <%= link_to '<i class="fa fa-plus"> </i> Add a New Partner'.html_safe , new_partner_path  %> | 
    <%= link_to '<i class="fa fa-pencil"></i> Edit Partner'.html_safe, edit_partner_path(@partner) %> |
    <%= link_to '<i class="fa fa-reply"></i> Back'.html_safe, partners_path %>
</h5>

<div class="row">
  <div class="col-md-4">
    <section class="widget">
      <div class="panel-header"><i class="fa fa-user"></i> <%= @partner.contact_name %></div>
      <div class="panel-body">
        <div class="row">
          <p>
            <strong>Email:</strong>
            <%= @partner.email %>
          </p>
          <p>
            <strong>Phone:</strong>
            <%= @partner.phone_num %>
          </p>
        </div>
      </div>
    </section>
  </div>
  <% if @partner.secondary_contact_name.present? %>
  <div class="col-md-4">
    <section class="widget">
      <div class="panel-header"><i class="fa fa-user"></i> <%= @partner.secondary_contact_name %></div>
      <div class="panel-body">
        <div class="row">
          <p>
            <strong>Email:</strong>
            <%= @partner.secondary_email %>
          </p>
          <p>
            <strong>Phone:</strong>
            <%= @partner.secondary_phone_num %>
          </p>
        </div>
      </div>
    </section>
  </div>
  <% end %>
</div>


<%= link_to 'Edit', edit_partner_path(@partner) %> |
<%= link_to 'Back', partners_path %>